'use client';

import { Target, Sparkles, Palette, Check, Heart, RefreshCw, Map as MapIcon, BarChart2, Download, Rocket, CheckCircle } from 'lucide-react';

interface StrategyDashboardProps {
  swot: { strengths: string[], weaknesses: string[], opportunities: string[], threats: string[] };
  names: { n: string, m: string }[];
  branding: { styles: any[] };
  roadmap: { time: string, title: string, desc: string }[];
  scorecard: { planning: number, financial: number, marketing: number, launch: number };
}

export default function StrategyDashboard({ swot, names, branding, roadmap, scorecard }: StrategyDashboardProps) {
  const SWOTBox = ({ title, items, icon: Icon, color }: any) => (
    <div className="bg-white/5 border border-white/10 rounded-xl p-3">
      <div className="flex items-center gap-2 mb-2">
        <div className={`w-6 h-6 rounded flex items-center justify-center bg-${color}-500/20`}>
          <Icon className={`w-3.5 h-3.5 text-${color}-400`} />
        </div>
        <span className="font-bold text-white text-xs">{title}</span>
      </div>
      <ul className="space-y-1.5 ml-1">
        {items.map((i: string, idx: number) => (
          <li key={idx} className="text-[10px] text-gray-300 flex gap-1.5">
            <span className={`text-${color}-400 mt-0.5`}>•</span>
            <span>{i}</span>
          </li>
        ))}
      </ul>
    </div>
  );

  return (
    <div className="bg-black/40 border border-white/10 rounded-2xl p-4 shadow-2xl backdrop-blur-md w-full max-w-md animate-[fadeIn_0.5s_ease-out] mt-4">
      <div className="flex justify-between items-start mb-5 border-b border-white/10 pb-3">
        <div>
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <Rocket className="w-5 h-5 text-violet-400" /> Business Strategy
          </h2>
          <p className="text-[10px] text-gray-400 uppercase tracking-wider mt-1">Generated by AI Strategist</p>
        </div>
        <div className="w-10 h-10 rounded-full bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center">
          <CheckCircle className="w-5 h-5 text-emerald-400" />
        </div>
      </div>

      {/* SWOT */}
      <div className="mb-6">
        <h3 className="text-xs font-bold text-violet-300 uppercase tracking-widest mb-3 flex items-center gap-2">
          <Target className="w-4 h-4" /> SWOT Analysis
        </h3>
        <div className="grid grid-cols-2 gap-2">
          <SWOTBox title="Strengths" items={swot.strengths} icon={Target} color="emerald" />
          <SWOTBox title="Weaknesses" items={swot.weaknesses} icon={Target} color="red" />
          <SWOTBox title="Opportunities" items={swot.opportunities} icon={Target} color="blue" />
          <SWOTBox title="Threats" items={swot.threats} icon={Target} color="orange" />
        </div>
      </div>

      {/* Names */}
      <div className="mb-6">
        <h3 className="text-xs font-bold text-violet-300 uppercase tracking-widest mb-3 flex items-center gap-2">
          <Sparkles className="w-4 h-4" /> AI Name Generator
        </h3>
        <div className="space-y-2">
          {names.map((item, idx) => (
            <div key={idx} className="bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg p-2.5 flex items-center justify-between group transition-colors">
              <div>
                <div className="text-sm font-bold text-white mb-0.5">{item.n}</div>
                <div className="text-[9px] text-gray-400">{item.m}</div>
              </div>
              <div className="flex gap-1.5 opacity-50 group-hover:opacity-100 transition-opacity">
                <button className="w-6 h-6 rounded bg-white/10 flex items-center justify-center hover:text-emerald-400"><Check className="w-3 h-3" /></button>
                <button className="w-6 h-6 rounded bg-white/10 flex items-center justify-center hover:text-pink-400"><Heart className="w-3 h-3" /></button>
              </div>
            </div>
          ))}
          <button className="w-full mt-2 py-2 rounded-lg border border-violet-500/30 text-violet-300 text-xs font-semibold hover:bg-violet-500/10 transition-colors flex items-center justify-center gap-2">
            <RefreshCw className="w-3.5 h-3.5" /> Generate More Names
          </button>
        </div>
      </div>

      {/* Roadmap */}
      <div className="mb-6">
        <h3 className="text-xs font-bold text-violet-300 uppercase tracking-widest mb-3 flex items-center gap-2">
          <MapIcon className="w-4 h-4" /> 90-Day Roadmap
        </h3>
        <div className="bg-white/5 border border-white/10 rounded-xl p-4">
          {roadmap.map((step, idx) => (
            <div key={idx} className="relative pl-6 pb-4 last:pb-0">
              <div className="absolute left-1.5 top-1.5 bottom-0 w-px bg-white/10 last:bg-transparent"></div>
              <div className="absolute left-0 top-1.5 w-3.5 h-3.5 rounded-full bg-violet-500/20 border border-violet-400 flex items-center justify-center">
                <div className="w-1.5 h-1.5 rounded-full bg-violet-400"></div>
              </div>
              <div className="text-[10px] font-bold text-violet-400 mb-0.5">{step.time}</div>
              <div className="text-xs font-bold text-white">{step.title}</div>
              <div className="text-[10px] text-gray-400">{step.desc}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Scorecard */}
      <div className="mb-2">
        <h3 className="text-xs font-bold text-violet-300 uppercase tracking-widest mb-3 flex items-center gap-2">
          <BarChart2 className="w-4 h-4" /> Business Scorecard
        </h3>
        <div className="bg-white/5 border border-white/10 rounded-xl p-3">
          {Object.entries(scorecard).map(([key, val], idx) => {
            const colors = ['emerald', 'blue', 'amber', 'violet'];
            return (
              <div key={key} className="flex items-center justify-between mb-1.5">
                <span className="text-[10px] text-gray-300 capitalize">{key}</span>
                <div className="flex items-center gap-2 w-1/2">
                  <div className="h-1.5 flex-1 bg-white/10 rounded-full overflow-hidden">
                    <div className={`h-full bg-${colors[idx%4]}-400 rounded-full`} style={{ width: `${val}%` }}></div>
                  </div>
                  <span className="text-[9px] font-mono text-white">{val}</span>
                </div>
              </div>
            );
          })}
          
          <div className="mt-4 pt-3 border-t border-white/10">
            <div className="text-[10px] uppercase text-gray-500 font-semibold mb-2">Export Center (Coming Soon)</div>
            <div className="grid grid-cols-2 gap-2">
              {['Business Plan PDF', 'Pitch Deck', 'Financial Report', 'Marketing Plan'].map((e, i) => (
                <div key={i} className="bg-white/5 border border-white/10 rounded p-1.5 text-[9px] text-gray-300 flex items-center gap-1.5 cursor-pointer hover:bg-white/10">
                  <Download className="w-3 h-3 text-violet-400" /> {e}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

    </div>
  );
}
